import {infer}from'./model-v002.mjs';import {TOPICS,FORMS,topicFor,compare,counterexamples,ratio,fmt}from'./math.mjs';
const $=id=>document.getElementById(id);let model=null;let active=null;let suggestion=null;
for(const t of TOPICS){const o=document.createElement('option');o.value=t.id;o.textContent=t.name;$('topic').append(o);}
for(const[k,f]of Object.entries(FORMS)){const o=document.createElement('option');o.value=k;o.textContent=f.name;$('meaning').append(o);}
function reset(){active=null;suggestion=null;$('results').hidden=true;$('empty-state').hidden=false;$('meaning').value='';$('run').disabled=true;$('reflection').value='';$('download-status').textContent='';$('errors').textContent='';$('model-status').textContent='A small local model suggests a meaning. You always confirm it.';$('evidence').textContent='';$('experiment-state').textContent='Waiting for confirmation';}
function showTopic(){const t=topicFor($('topic').value);$('formula').textContent=t.formula;$('assumptions').textContent=t.assumptions;reset();}
$('topic').addEventListener('change',showTopic);$('explanation').addEventListener('input',reset);
$('meaning').addEventListener('change',()=>{active=null;$('results').hidden=true;$('empty-state').hidden=false;$('reflection').value='';$('download-status').textContent='';$('experiment-state').textContent='Waiting for confirmation';$('run').disabled=!Object.hasOwn(FORMS,$('meaning').value);});
$('interpret').addEventListener('click',()=>{active=null;$('results').hidden=true;$('empty-state').hidden=false;$('reflection').value='';$('download-status').textContent='';$('experiment-state').textContent='Waiting for confirmation';try{if(!model)throw new Error('The local model has not loaded. Choose a meaning yourself.');const text=$('explanation').value;if(!text.trim())throw new Error('Write an explanation first, or choose the meaning yourself.');suggestion=infer(model,text);$('errors').textContent='';if(suggestion.deferred){$('model-status').textContent='Please choose the meaning yourself. '+suggestion.reasons.join(' ');$('meaning').value='';$('run').disabled=true;}else{$('model-status').textContent='Suggested: '+FORMS[suggestion.label].name+'. Model score '+fmt(suggestion.score)+' (uncalibrated). Confirm or change it.';$('meaning').value=suggestion.label;$('run').disabled=false;}$('evidence').textContent=suggestion.deferred?'The model has not chosen an interpretation.':'Words contributing to this suggestion: '+suggestion.evidence.map(x=>x.feature.replaceAll('_',' ')).join(', ')+'.';}catch(e){$('errors').textContent=e.message;}});
function svgEl(name,attrs={},text){const e=document.createElementNS('http://www.w3.org/2000/svg',name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;}
function draw(t,claim,scale){const plot=$('plot');while(plot.lastChild)plot.removeChild(plot.lastChild);plot.append(svgEl('title',{id:'plot-title'},'Normalized scaling comparison'),svgEl('desc',{id:'plot-description'},'Dashed claim and solid model curves. Exact values are available in the comparison table.'));
 const samples=Array.from({length:76},(_,i)=>.25+i*.05);const max=Math.max(...samples.map(s=>ratio(s,t.power)),...samples.map(s=>ratio(s,FORMS[claim].power)));const x=s=>48+(s-.25)/3.75*470,y=v=>220-v/max*192;
 for(const n of[0,max/2,max]){plot.append(svgEl('line',{x1:48,x2:518,y1:y(n),y2:y(n),stroke:'#dce5e6'}),svgEl('text',{x:41,y:y(n)+4,'text-anchor':'end'},fmt(n)));}
 for(const n of[.5,1,2,4]){plot.append(svgEl('line',{x1:x(n),x2:x(n),y1:220,y2:224,stroke:'#a7bbbf'}),svgEl('text',{x:x(n),y:240,'text-anchor':'middle'},fmt(n)+'×'));}
 plot.append(svgEl('text',{x:48,y:14},'Output ratio'),svgEl('text',{x:518,y:257,'text-anchor':'end'},'Input ratio'));
 for(const[power,color,dash]of[[FORMS[claim].power,'#bd4b36','7 5'],[t.power,'#00796b','']]){const d=samples.map((s,i)=>(i?'L':'M')+x(s).toFixed(2)+' '+y(ratio(s,power)).toFixed(2)).join(' ');plot.append(svgEl('path',{d,fill:'none',stroke:color,'stroke-width':3,'stroke-dasharray':dash}));plot.append(svgEl('circle',{cx:x(scale),cy:y(ratio(scale,power)),r:5,fill:color,stroke:'#ffffff','stroke-width':2}));}
}
function render(){if(!active)return;const t=topicFor(active.topic),scale=Number($('scale').value),v=compare(t.id,active.claim,scale);$('scale-value').textContent=fmt(scale)+'×';$('scale-context').textContent='Change '+t.input+'; compare '+t.output+' while the stated assumptions stay fixed.';$('predicted').textContent=fmt(v.predicted)+'×';$('expected').textContent=fmt(v.expected)+'×';draw(t,active.claim,scale);
 const rows=counterexamples(t.id,active.claim);$('comparison-rows').replaceChildren(...rows.map(r=>{const tr=document.createElement('tr');for(const n of[r.scale,r.predicted,r.expected]){const td=document.createElement('td');td.textContent=fmt(n)+'×';tr.append(td);}return tr;}));$('why').textContent=t.why+' '+t.assumptions;
 const mismatch=rows.find(r=>r.differs);$('finding').textContent=mismatch?'Counterexample: at '+fmt(mismatch.scale)+'× '+t.input+', your interpretation predicts '+fmt(mismatch.predicted)+'× '+t.output+'. The stated relationship gives '+fmt(mismatch.expected)+'×. '+t.why:'Your selected scaling form agrees with this ideal model at the tested scales. This comparison alone does not prove your explanation or a real-world system is correct.';$('experiment-state').textContent='Meaning confirmed by you';}
$('run').addEventListener('click',()=>{try{if(!$('explanation').value.trim())throw new Error('Write your prediction before running the experiment.');if(!Object.hasOwn(FORMS,$('meaning').value))throw new Error('Confirm your meaning first.');active={topic:$('topic').value,claim:$('meaning').value,explanation:$('explanation').value};$('results').hidden=false;$('empty-state').hidden=true;$('errors').textContent='';render();}catch(e){$('errors').textContent=e.message;}});$('scale').addEventListener('input',render);
$('download').addEventListener('click',()=>{if(!active)return;const t=topicFor(active.topic),v=compare(t.id,active.claim,Number($('scale').value));const text=['# Scale Lab experiment','',`System: ${t.name}`,`Formula: ${t.formula}`,`Assumptions: ${t.assumptions}`,'','## Original explanation',active.explanation,'',`Learner-confirmed meaning: ${FORMS[active.claim].name}`,`Current scale: ${fmt(v.scale)}x; prediction: ${fmt(v.predicted)}x; model: ${fmt(v.expected)}x`,'','## Comparison table','Input | Prediction | Model','--- | --- | ---',...counterexamples(t.id,active.claim).map(r=>`${fmt(r.scale)} | ${fmt(r.predicted)} | ${fmt(r.expected)}`),'','## Learner reflection',$('reflection').value||'(Not yet written.)','','Synthetic-model prototype. No grade, measurement or learning-gain claim. Explanations are included only because you requested this local download.'].join('\n');const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='scale-lab-experiment.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('download-status').textContent='The page requested a Markdown download. Check your browser download destination.';});
showTopic();
try{const responses=await Promise.all([fetch('./model-v002.json'),fetch('./evaluation-v002.json')]);if(responses.some(r=>!r.ok))throw new Error('Local model files could not be read.');const loaded=await Promise.all(responses.map(r=>r.json()));model=loaded[0];const e=loaded[1];$('evaluation-note').textContent=`Validation: ${e.validation.rawCorrect}/${e.validation.n} raw class matches; ${e.validation.acceptedCorrect}/${e.validation.accepted} non-deferred matches. The initial test was already examined during development and is not fresh evidence. Independent authored synthetic review: 13/30 raw matches, 26/30 deferred, 3/4 non-deferred matches (including one confident error); 10/10 unsupported examples deferred. This small language model is unreliable and only optional. No real learners were evaluated.`;}catch(e){$('model-status').textContent='Model unavailable. You can still select a meaning and run the mathematical experiment.';$('evaluation-note').textContent=e.message;}
