import {parsePoints,fitPowerLaw,predictFit,probeFit}from'./power-fit.mjs';import{fmt}from'./math.mjs';
const $=id=>document.getElementById(id);let fit=null,probe=null;
function clearProbe() {probe=null;$('probe-result').textContent='The probe has not been tested.';}
function reset() {fit=null;clearProbe();$('fit-result').textContent='Fit the observations to learn an exponent and a constant.';$('fit-rows').replaceChildren();$('probe-button').disabled=true;$('fit-download').disabled=true;$('fit-error').textContent='';$('fit-download-status').textContent='';}
$('observations').addEventListener('input',reset);for(const id of['probe-x','probe-y'])$(id).addEventListener('input',clearProbe);
$('fit-button').addEventListener('click',()=>{reset();try{fit=fitPowerLaw(parsePoints($('observations').value));$('fit-result').textContent=`Learned curve: output = ${fmt(fit.constant)} × input^${fmt(fit.power)}. Fit on ${fit.n} observations. Log-space training RMSE ${fmt(fit.logRmse)}. This is a fitted relationship, not a verified physical law.`;
 $('fit-rows').replaceChildren(...fit.points.map(p=>{const tr=document.createElement('tr');for(const v of[p.x,p.y,predictFit(fit,p.x)]){const td=document.createElement('td');td.textContent=fmt(v);tr.append(td);}return tr;}));$('probe-button').disabled=false;$('fit-download').disabled=false;}catch(e){$('fit-error').textContent=e.message;}});
$('probe-button').addEventListener('click',()=>{try{if(!fit)throw new Error('Fit the observations first.');if(!$('probe-x').value.trim()||!$('probe-y').value.trim())throw new Error('Enter both probe values.');probe=probeFit(fit,{x:Number($('probe-x').value),y:Number($('probe-y').value)});$('fit-error').textContent='';$('probe-result').textContent=`At input ${fmt(probe.x)}, the frozen fitted curve predicts ${fmt(probe.predicted)}; your separate observation is ${fmt(probe.y)}. Relative error: ${fmt(probe.relativeError*100)}%. ${probe.outsideFitRange?'This is outside the fitting range (extrapolation). ':''}${probe.relativeError>.2?'This probe challenges the fitted curve.':'This one probe is consistent within the fixed 20% comparison tolerance.'} The probe did not update the model, and this check cannot establish general accuracy.`;}catch(e){clearProbe();$('fit-error').textContent=e.message;}});
$('fit-download').addEventListener('click',()=>{if(!fit)return;const text=['# Scale Lab fitted experiment','',`Method: ${fit.kind}`,`Fit rows: ${fit.n}`,`Learned exponent: ${fit.power}`,`Learned constant: ${fit.constant}`,`Log-space training RMSE: ${fit.logRmse}`,'','## Fitting data','Input, output',...fit.points.map(p=>`${p.x}, ${p.y}`),'','## Separate probe',probe?JSON.stringify(probe,null,2):'(Not tested.)','','The separate probe was not used to fit this curve. Small positive numeric data only; no generalization or learning-gain claim. Default example points are synthetic.'].join('\n');const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='scale-lab-fitted-experiment.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('fit-download-status').textContent='The page requested a local Markdown download.';});
reset();
