import {writeFile}from'node:fs/promises';import {createHash}from'node:crypto';import {rows,OOD}from'../corpus.mjs';import {train,infer}from'../model-v002.mjs';
const training=rows('train'),validation=rows('validation');let chosen=null;const candidates=[];
for(const reg of[0.0001,0.001,0.005]){const m=train(training,reg);const raw=validation.filter(r=>infer(m,r.text).label===r.label).length;candidates.push({reg,validationRawCorrect:raw});if(!chosen||raw>chosen.raw)chosen={m,raw};}
const model=chosen.m;let threshold=0.95;
for(const score of[0.4,0.5,0.6,0.7,0.8,0.9,0.95]){model.threshold={score,margin:0.1,coverage:0.25};if(validation.every(r=>{const p=infer(model,r.text);return p.deferred||p.label===r.label;})){threshold=score;break;}}
model.threshold={score:threshold,margin:0.1,coverage:0.25};
function evaluate(data){const out=data.map(r=>{const p=infer(model,r.text);return {...r,predicted:p.label,score:p.score,deferred:p.deferred,reasons:p.reasons};});const accepted=out.filter(r=>!r.deferred);return {n:out.length,rawCorrect:out.filter(r=>r.predicted===r.label).length,accepted:accepted.length,acceptedCorrect:accepted.filter(r=>r.predicted===r.label).length,rows:out};}
const report={scope:'Authored synthetic English explanations only. Initial test is now a seen development set and is not fresh held-out evidence.',trainCount:training.length,candidates,selectedRegularization:model.regularization,validation:evaluate(validation),seenDevelopmentTest:evaluate(rows('test')),ood:OOD.map(text=>({text,...infer(model,text)})),threshold:model.threshold,corpusSha256:createHash('sha256').update(JSON.stringify([...training,...validation,...rows('test')])).digest('hex'),freshHoldout:'Pending independent reviewer-authored sealed corpus; not used for fitting or selection.',limitations:['Synthetic language only, no learner study.','Lexical linear classifier; no language-model semantics or guaranteed understanding.','Scores are uncalibrated. Every suggestion requires user confirmation.','Preprocessing has declared English word normalization; the model weights are learned from the training rows.']};
await writeFile(new URL('../model-v002.json',import.meta.url),JSON.stringify(model),{flag:'wx'});await writeFile(new URL('../evaluation-v002.json',import.meta.url),JSON.stringify(report,null,2),{flag:'wx'});
console.log(JSON.stringify({train:48,candidates,validation:{n:report.validation.n,correct:report.validation.rawCorrect,accepted:report.validation.accepted,acceptedCorrect:report.validation.acceptedCorrect},seenDevelopmentTest:{n:24,correct:report.seenDevelopmentTest.rawCorrect},threshold:model.threshold}));
